version: "3.9"

services:
  hmt_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: hmt_app
    restart: always
    depends_on:
      - mysql_hmt
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:EerF9HppDo22DRmN1w7OoTK/VPy5UxYk5JvCZqbY+UM=
      DB_CONNECTION: mysql
      DB_HOST: mysql_hmt
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - laravel_net

  nginx_hmt:
    image: nginx:stable-alpine
    container_name: nginx_hmt
    restart: always
    ports:
      - "8800:80"
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./public:/var/www/html/public:ro
    depends_on:
      - hmt_app
    networks:
      - laravel_net

  mysql_hmt:
    image: mysql:8.3
    container_name: mysql_hmt
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_net

volumes:
  db_data:

networks:
  laravel_net:
    driver: bridge
