services:
  hmt_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: hmt_app
    restart: always
    depends_on:
      - mysql_hmt
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:EerF9HppDo22DRmN1w7OoTK/VPy5UxYk5JvCZqbY+UM=
      DB_CONNECTION: mysql
      DB_HOST: mysql_hmt
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - app_code:/var/www/html        # share volume berisi app code
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - laravel_net

  nginx_hmt:
    image: nginx:stable-alpine
    container_name: nginx_hmt
    restart: always
    ports:
      - "8800:80"
    depends_on:
      - hmt_app
    volumes:
      - app_code:/var/www/html:ro     # mount volume yang sama (read-only)
      - ./storage:/var/www/html/storage
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel_net

  mysql_hmt:
    image: mysql:8.3
    container_name: mysql_hmt
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

volumes:
  db_data:
  app_code:

networks:
  laravel_net:
    driver: bridge
